### ISSUE TITLE
TODO for 4.0

### ISSUE THREAD

**Issue by Exxarion** [Exxarion/WorldGM#6]
* [x] Add console support
* [x] Re-add the (world) parameter
* [x] Fix a bug with creative mode switching
* [x] Debugging and cleanup
